package promise.app_base.error;

import java.lang.System;

@kotlin.Metadata(mv = {1, 1, 15}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u0016\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\b\n\u0000\u0018\u00002\u00060\u0001j\u0002`\u0002B\u0005\u00a2\u0006\u0002\u0010\u0003J\u0006\u0010\u0004\u001a\u00020\u0005J\u000e\u0010\u0004\u001a\u00020\u00002\u0006\u0010\u0004\u001a\u00020\u0005R\u000e\u0010\u0004\u001a\u00020\u0005X\u0082\u000e\u00a2\u0006\u0002\n\u0000\u00a8\u0006\u0006"}, d2 = {"Lpromise/app_base/error/AuthError;", "Ljava/lang/Exception;", "Lkotlin/Exception;", "()V", "code", "", "appbase_debug"})
public final class AuthError extends java.lang.Exception {
    private int code;
    
    public final int code() {
        return 0;
    }
    
    @org.jetbrains.annotations.NotNull()
    public final promise.app_base.error.AuthError code(int code) {
        return null;
    }
    
    public AuthError() {
        super();
    }
}